# Generated by Django 5.2.7 on 2025-10-23 00:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrinho', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='caritem',
            name='esta_disponivel',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='caritem',
            name='car',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='carrinho.carrinho'),
        ),
    ]
