# Generated by Django 5.2.7 on 2025-10-09 00:16

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='slug',
            field=autoslug.fields.AutoSlugField(always_update=True, editable=True, populate_from='produto_nome', unique=True),
        ),
    ]
